CREATE DATABASE aerolinea;

USE aerolinea;

CREATE TABLE pasajeros (
  NM_ID INT NOT NULL AUTO_INCREMENT COMMENT 'CODIGO IDENTIFICADOR',
  NM_ID_VUELO INT NOT NULL COMMENT 'ID VUELO',
  DS_NOMBRES varchar(200) NOT NULL COMMENT 'NOMBRES',
  DS_APELLIDOS varchar(200) NOT NULL COMMENT 'APELLIDOS',
  DS_GENERO varchar(200) NOT NULL COMMENT 'GENERO',
  DS_TIPO_IDENTIFICACION varchar(200) NOT NULL COMMENT 'TIPO IDENTIFICACION',
  DS_IDENTIFICACION varchar(200) NOT NULL COMMENT 'NUMERO DE IDENTIFICACION',
  DS_CELULAR varchar(200) NOT NULL COMMENT 'NUMERO CELULAR',
  DS_EMAIL varchar(200) NOT NULL COMMENT 'CORREO ELECTRONICO',
  PRIMARY KEY (NM_ID));

CREATE TABLE vuelos (
  NM_ID INT NOT NULL AUTO_INCREMENT COMMENT 'CODIGO IDENTIFICADOR',
  NM_ID_PASAJERO INT NOT NULL COMMENT 'ID PASAJERO',
  NM_NUMERO_VUELO INT NOT NULL COMMENT 'NUMERO DE VUELO',
  DS_ORIGEN VARCHAR(200) NOT NULL COMMENT 'ORIGEN',
  DS_DESTINO VARCHAR(200) NOT NULL COMMENT 'DESTINO',
  DS_HORA VARCHAR(200) NOT NULL COMMENT 'HORA VUELO',
  FE_FECHA VARCHAR(200) NOT NULL COMMENT 'FECHA DE VUELO',
  PRIMARY KEY (NM_ID));

CREATE TABLE aviones (
  ID_AVION INT NOT NULL AUTO_INCREMENT COMMENT 'CODIGO IDENTIFICADOR',
  NM_ID_VUELO_PASAJERO INT NOT NULL COMMENT 'ID VUELO Y PASAJERO',
  DS_TIPO VARCHAR(200) NOT NULL COMMENT 'TIPO DE AVION',
  NM_NUMERO_PASAJEROS VARCHAR(45) NOT NULL COMMENT 'NUMERO DE PASAJEROS',
  PRIMARY KEY (ID_AVION));

INSERT INTO aviones (NM_ID_VUELO_PASAJERO, DS_TIPO, NM_NUMERO_PASAJEROS) 
VALUES (1, 'comercial', 20);

INSERT INTO aviones (NM_ID_VUELO_PASAJERO, DS_TIPO, NM_NUMERO_PASAJEROS) 
VALUES (2, 'comercial', 15);

INSERT INTO aviones (NM_ID_VUELO_PASAJERO, DS_TIPO, NM_NUMERO_PASAJEROS) 
VALUES (3, 'comercial', 5);

INSERT INTO pasajeros (NM_ID_VUELO, DS_NOMBRES, DS_APELLIDOS, DS_GENERO, DS_TIPO_IDENTIFICACION, DS_IDENTIFICACION, DS_CELULAR, DS_EMAIL)
VALUES (1, 'cristian', 'cortes', 'masculino', 'cedula', 1765435643, 2312345677, 'cotes@cortes.com');

INSERT INTO pasajeros (NM_ID_VUELO, DS_NOMBRES, DS_APELLIDOS, DS_GENERO, DS_TIPO_IDENTIFICACION, DS_IDENTIFICACION, DS_CELULAR, DS_EMAIL)
VALUES (1, 'felipe', 'pelaez', 'masculino', 'cedula', 1987675847, 1232134322, 'pelaez@pelaez.com');

INSERT INTO pasajeros (NM_ID_VUELO, DS_NOMBRES, DS_APELLIDOS, DS_GENERO, DS_TIPO_IDENTIFICACION, DS_IDENTIFICACION, DS_CELULAR, DS_EMAIL)
VALUES (1, 'santiago', 'garcia', 'masculino', 'cedula', 2765465783, 2312344433, 'garcia@garcia.com');

INSERT INTO pasajeros (NM_ID_VUELO, DS_NOMBRES, DS_APELLIDOS, DS_GENERO, DS_TIPO_IDENTIFICACION, DS_IDENTIFICACION, DS_CELULAR, DS_EMAIL)
VALUES (2, 'camilo', 'suaza', 'masculino', 'cedula', 2754676543, 3456545677, 'suaza@suaza.com');

INSERT INTO vuelos (NM_ID_PASAJERO, NM_NUMERO_VUELO, DS_ORIGEN, DS_DESTINO, DS_HORA, FE_FECHA)
VALUES (1, 1, 'medellin', 'bogota', '08:00', '2020-11-09');

INSERT INTO vuelos (NM_ID_PASAJERO, NM_NUMERO_VUELO, DS_ORIGEN, DS_DESTINO, DS_HORA, FE_FECHA)
VALUES (2, 1, 'bogota', 'medellin', '08:00', '2020-11-09');
